### ISSUE TITLE
iOS build failed with crashlytic module

### ISSUE THREAD

**Issue by sandeep14** [hansemannn/titanium-crashlytics#11]
Hi,

I  am using crashlytics Module of version 1.2.1 .
 it Build & run in simulator properly
 But on firebase Console is showing upload 1 Missing DySM  
refer screenshots
![Screenshot 2019-03-12 at 3 36 04 PM](https://user-images.githubusercontent.com/5755440/54191797-a26c2100-44dc-11e9-8f03-4a152c78c8d7.png)

When I tried to created adhoc build  . during build process it throw below error
[ERROR] :  ** ARCHIVE FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	PhaseScriptExecution [Ti]\ Crashlytics /Users/admin/Documents/Appcelerator_Studio_Workspace/test/build/iphone/build/Intermediates/test.build/Release-iphoneos/test.build/Script-000000000000000000000032.sh
[ERROR] :  (1 failure)

**Comment by deckameron** [comment]
@sandeep14 how did you manage to solve it?

**Comment by sandeep14** [comment]
I just changed the crashlytics module version it get start working. also we just added this line "../../modules/iphone/ti.crashlytics/1.2.1/platform/Fabric.framework/uploadDSYM" in script-titanium-crashlytics.sh

**Comment by arunraj-qburst** [comment]
I am also getting the same error 
```
[ERROR] :  ** ARCHIVE FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	PhaseScriptExecution [Ti]\ Crashlytics /Users/arunrajsaraswathy/Documents/Appcelerator_Studio_Workspace/---<app name here> ---/Script-000000000000000000000047.sh
[ERROR] :  (1 failure)
```
I alos noticed that the path and version of ti.crashlytics has changed. 
Would be really great and appreciated if someone can help us to resolve this issue.


ti.crashlytics: ti.crashlytics/4.0.0/platform/FirebaseCrashlytics
Ti SDK: 9.3.2GA
iOS: 14+
