### ISSUE TITLE
How to create a new Fabric app?

### ISSUE THREAD

**Issue by Sean-Brown-Digi** [hansemannn/titanium-crashlytics#14]
I'm new to Crashlytics, but I want to add it to an existing Alloy app, however it does not work. I've followed the directions in the README, using the my organization's keys, but every time I run the app I see this error:
```
ERROR] CrashlyticsCore: .
[ERROR] CrashlyticsCore: .     |  |
[ERROR] CrashlyticsCore: .     |  |
[ERROR] CrashlyticsCore: .     |  |
[ERROR] CrashlyticsCore: .   \ |  | /
[ERROR] CrashlyticsCore: .    \    /
[ERROR] CrashlyticsCore: .     \  /
[ERROR] CrashlyticsCore: .      \/
[ERROR] CrashlyticsCore: .
[ERROR] CrashlyticsCore: This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
[ERROR] CrashlyticsCore: install an Android build tool and ask a team member to invite you to this app's organization.
[ERROR] CrashlyticsCore: .
[ERROR] CrashlyticsCore: .      /\
[ERROR] CrashlyticsCore: .     /  \
[ERROR] CrashlyticsCore: .    /    \
[ERROR] CrashlyticsCore: .   / |  | \
[ERROR] CrashlyticsCore: .     |  |
[ERROR] CrashlyticsCore: .     |  |
[ERROR] CrashlyticsCore: .     |  |
```

The app doesn't crash, however the the app also never shows up in the Fabric dashboard. I've looked at the [directions to create a Fabric app](https://fabric.io/kits/ios/crashlytics) and it mentions modifying the Android/iOS projects directly, but this is Titanium where you don't directly create an Android/iOS app, so how am I supposed to create the Fabric app?

**Comment by Sean-Brown-Digi** [comment]
Also as a test I tried to run the demo project but it doesn't build: `[ERROR] Application not registered.`

**Comment by orl99** [comment]
@Sean-Brown-Digi do you have some news?
I was reading that fabric will no longer be supported and will be replaced totally by firebase.
soo, will this module be supported?

**Comment by Sean-Brown-Digi** [comment]
Sorry but unfortunately I didn't have much luck. I emailed Crashlytics support and they told me that Titanium isn't officially supported. Since I'm so busy at work I gave up on this path.

**Comment by hansemannn** [comment]
Fabric is not required anymore in the new Firebase environment. Closing!
