### ISSUE TITLE
Appcelerator Package Build Fails 

### ISSUE THREAD

**Issue by ericrab** [hansemannn/titanium-crashlytics#15]
[ERROR] :  ** ARCHIVE FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	PhaseScriptExecution [Ti]\ Crashlytics /Users/peterladis/Documents/products.nosync/devices.nosync/IOS/build/iphone/build/Intermediates/LilyPad.build/Release-iphoneos/LilyPad.build/Script-000000000000000000000026.sh
[ERROR] :  (1 failure)

Any ideas how to fix?

**Comment by hansemannn** [comment]
It means that the shell script errored, probably either a syntax error or invalid API keys.

**Comment by ericrab** [comment]
Can I send you a copy....I am able to run this in simulator just fine and it uploads to fabric just fine??

**Comment by ericrab** [comment]
This is my SH

# Do not run this file manually! It is referenced from your native Xcode project
"../../modules/iphone/ti.crashlytics/1.2.2/platform/Fabric.framework/uploadDSYM" bcb14b5a7a1d4538da18a93868070240513e595b 24f401ab77d58868ab729625408c7a54bc77a2e7951ebbce293ac0ba0949b964

**Comment by ericrab** [comment]
The path seems off to me....my module is installed in my Application Support directory

**Comment by deckameron** [comment]
@ericrab did you manage to solve this issue? Could you share how, please?
