### ISSUE TITLE
Cannot build for production

### ISSUE THREAD

**Issue by ericrab** [hansemannn/titanium-crashlytics#17]
1. I added Modules to my project
2. Build for production ...same errors....attached is a picture of the error..and my project. 
3. Triple verified that the API KEY and secret are correct.

Please advise
<img width="1155" alt="Screen Shot 2019-04-17 at 9 28 11 PM" src="https://user-images.githubusercontent.com/1727354/56330899-15aa2800-6158-11e9-91f1-02e966b4378e.png">
<img width="412" alt="Screen Shot 2019-04-17 at 9 28 05 PM" src="https://user-images.githubusercontent.com/1727354/56330900-15aa2800-6158-11e9-9b8b-e435dd2b5063.png">

**Comment by hansemannn** [comment]
what does your shell script look like?

**Comment by ericrab** [comment]
Ive tried 

# Do not run this file manually! It is referenced from your native Xcode project
"../modules/iphone/ti.crashlytics/1.2.2/platform/Fabric.framework/uploadDSYM" myapikey mysecret


and 


# Do not run this file manually! It is referenced from your native Xcode project
"../../modules/iphone/ti.crashlytics/1.2.2/platform/Fabric.framework/uploadDSYM" myapikyu my secret

**Comment by ericrab** [comment]
This is trying to auto upload the DSYM...cna I just manually send to the fabric site

**Comment by ericrab** [comment]
Here is the exact error from the build log:

[TRACE]      /bin/sh -c /Users/peterladis/Documents/products.nosync/devices.nosync/IOS/build/iphone/build/Intermediates/LilyPad.build/Release-iphoneos/LilyPad.build/Script-000000000000000000000026.sh
[TRACE]  /bin/bash: ../../scripts/script-titanium-crashlytics.sh: No such file or directory
[TRACE]  Command PhaseScriptExecution failed with a nonzero exit code
[ERROR]  ** ARCHIVE FAILED **

**Comment by ericrab** [comment]
Added scripts in again and got this

/bin/sh -c /Users/peterladis/Documents/products.nosync/devices.nosync/IOS/build/iphone/build/Intermediates/LilyPad.build/Release-iphoneos/LilyPad.build/Script-000000000000000000000026.sh
[TRACE]  ../../scripts/script-titanium-crashlytics.sh: line 1: ../../modules/iphone/ti.crashlytics/1.2.2/platform/Fabric.framework/uploadDSYM: No such file or directory
[TRACE]  Command PhaseScriptExecution failed with a nonzero exit code
[ERROR]  ** ARCHIVE FAILED **

**Comment by ericrab** [comment]
Here is a picture of my IOS director during a build

![Screen Shot 2019-04-18 at 11 28 30 AM](https://user-images.githubusercontent.com/1727354/56372506-25178880-61cd-11e9-87a0-904c45f3a816.png)

**Comment by ericrab** [comment]
More info..I changed the path to be the FULL path..and now I see a new error:

[TRACE]      /bin/sh -c /Users/peterladis/Documents/products.nosync/devices.nosync/IOS/build/iphone/build/Intermediates/LilyPad.build/Release-iphoneos/LilyPad.build/Script-000000000000000000000026.sh
[TRACE]  ../../scripts/script-titanium-crashlytics.sh: line 1: /Users/peterladis/Documents/products.nosync/devices.nosync/IOS/modules/iphone/ti.crashlytics/1.2.2/platform/Fabric.framework/uploadDSYM: Permission denied

**Comment by ericrab** [comment]
I fixed...had to go in and modify a bunch of file permissions

**Comment by hansemannn** [comment]
Happy you fixed it. For future reference: The Crashlytics script needs execution permissions (755).
