### ISSUE TITLE
Do you have a DIST for IOS for: hansemannn/titanium-imagepicker

### ISSUE THREAD

**Issue by ericrab** [hansemannn/titanium-crashlytics#18]
It will not compile on my system.

**Comment by ericrab** [comment]
Any updates?

**Comment by hansemannn** [comment]
This repo is for Crashlytics, sorry.

**Comment by hansemannn** [comment]
I added dist builds for iOS and Android [here](https://github.com/hansemannn/titanium-imagepicker/releases), but please do not spam other repos with requests about modules that are a different project.

**Comment by ericrab** [comment]
SWEET

**Comment by ericrab** [comment]
> I added dist builds for iOS and Android [here](https://github.com/hansemannn/titanium-imagepicker/releases), but please do not spam other repos with requests about modules that are a different project.

Sorry there was no way to comment on your  other REPO.
