### ISSUE TITLE
Android Not Reporting 

### ISSUE THREAD

**Issue by bubinf** [hansemannn/titanium-crashlytics#19]
My error is as follows

[ERROR] Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.deloitte.kitchensink/settings
[ERROR] Answers: Failed to retrieve settings
[WARN]  CrashlyticsCore: Received null settings, skipping report submission!

However, I also get this
[DEBUG] TitaniumCrashlyticsModule: (main) [981,981] Crashlytics initialized

Any help would be appreciated

**Comment by bubinf** [comment]
now it is this 
[ERROR] Fabric: Settings request failed.
[ERROR] APSAnalyticsRunnable: Unable to resolve host "api.appcelerator.com": No address associated with hostname
[ERROR] CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@49ff2b8
[ERROR] CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@65e9891
[ERROR] CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@9e953f6
[ERROR] CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@631e3f7
[ERROR] CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@ebd8264
[ERROR] CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@1c32ccd
[ERROR] APSAnalyticsRunnable: Unable to resolve host "api.appcelerator.com": No address associated with hostname

**Comment by caspahouzer** [comment]
How did you solve it

**Comment by bubinf** [comment]
It kind of started working.
Could have been the restart of my computer. The log out and log it of APPC
Or the manual Firebase configure 
 firebaseCore.configure({
			   APIKey: andAPI,
			   projectID: projectGoogleID,
			   applicationID: andID
			 });

This issue could also help you.
https://github.com/hansemannn/titanium-crashlytics/issues/20
