### ISSUE TITLE
SECRET_KEY

### ISSUE THREAD

**Issue by mirash8842** [hansemannn/titanium-crashlytics#21]
# Do not run this file manually! It is referenced from your native Xcode project
"../../modules/iphone/ti.crashlytics/1.2.1/platform/Fabric.framework/uploadDSYM" <YOUR_API_KEY> <YOUR_SECRET_KEY>

I'm using Firebase. Where can I find 'secret_key'?

**Comment by hansemannn** [comment]
Please use the Firebase help channels for questions, thanks.
