### ISSUE TITLE
Android sdk 8.0.1.GA not calling onStart

### ISSUE THREAD

**Issue by Brianggalvez** [hansemannn/titanium-crashlytics#22]
Testing the new SDK the onStart override never gets called. With 8.0.0.GA I can see this log: CrashlyticsCore: Initializing Crashlytics 2.6.3.25

but with 8.0.1.GA It doesn't appears causing the following error:

` Error: Must Initialize Fabric before using singleton()`

**Comment by Wingee** [comment]
I see the same issue.That error appears in 8.0.1 but not on 8.0.0

**Comment by Wingee** [comment]
Error also exists on 8.0.2 SDK

**Comment by AndreaVitale** [comment]
Same here on 8.0.1

**Comment by guiu23** [comment]
In Android I see the same initialization with 8.0.0.GA but never notify about crashes of the app...

**Comment by macasfaj** [comment]
Same issue on Android using 8.2.1.GA

**Comment by hansemannn** [comment]
Please see the latest Android version!
