### ISSUE TITLE
Cannot get iOS module to work

### ISSUE THREAD

**Issue by Wingee** [hansemannn/titanium-crashlytics#24]
I've followed the installation instructions but Fabric just shows the spinning icon waiting for my app. I noticed in the logs it says:

[TRACE] :  Integrating static framework Fabric into Xcode project.
Not in production, skipping Crashlytics DSYM upload …

Which could be related. Any ideas?

**Comment by Wingee** [comment]
Will crashlytics only work with a production build of the app? @hansemannn ?

**Comment by bubinf** [comment]
Nice to have an answer, as I can't find a solution for this.

**Comment by bubinf** [comment]
I'm getting this

**Comment by Wingee** [comment]
@bubinf I managed to get it working but only with the 8.0.0 SDK. 8.0.1 caused the above error

**Comment by bubinf** [comment]
Figured it out. A Colleague had deleted the check for 
Not in production, skipping Crashlytics DSYM upload to solve the problem of Firebase not receiving Crash Reports.

Does that mean iOS will only work in production for sending Crash Reports?

**Comment by hansemannn** [comment]
Sorry for the issues guys. The production check should be removed and the latest commits are improving build time as well. It's best to debug it with the compiled project to make sure everything is injected properly.
