### ISSUE TITLE
Cannot build app iOS to production 1.2.2 sdk >= 8.0.0

### ISSUE THREAD

**Issue by ottopic** [hansemannn/titanium-crashlytics#25]
I'm getting this, anyway to fix it? 

[ERROR] ** ARCHIVE FAILED **
[ERROR] The following build commands failed:
[ERROR]         PhaseScriptExecution [Ti]\ Crashlytics /Script-000000000000000000000035.sh
[ERROR] (1 failure)

**Comment by deckameron** [comment]
@ottopic could you please share you solved this issue?

**Comment by ottopic** [comment]
I had not included https://github.com/hansemannn/titanium-firebase firebase core module.
