### ISSUE TITLE
Fabric shutdown

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-crashlytics#29]
With the message "Fabric is deprecated and shutting down May 4, 2020" isn't this module obsolete? or do I take it wrong?

**Comment by simtecsystem** [comment]
+1

**Comment by surajpendhare** [comment]
So, should i implement this module or no.


> +1

So, should i implement this module or no.

**Comment by rlustemberg** [comment]
I think the module is not obsolete, but might need an update. I'll have a look

**Comment by hansemannn** [comment]
I just moved Crashlytics to the new FirebaseCrashlytics. Give it a try!
