### ISSUE TITLE
Production build fails on PhaseScriptExecution Script-000000000000000000000041.sh

### ISSUE THREAD

**Issue by skypanther** [hansemannn/titanium-crashlytics#30]
Ti SDK version: 9.0.1.GA and 8.3.1.GA
Titanium CLI: 5.2.2
Alloy: 1.14.5
firebase-core: 2.2.0
ti-crashlytics: 1.2.2
firebase-analytics: 1.4.1
OS: Catalina 10.15.4

```
[ERROR] ** ARCHIVE FAILED **
[ERROR] The following build commands failed:
[ERROR]         PhaseScriptExecution [Ti]\ Crashlytics /Users/timpoulsen/repos/skypanther
/client_app/build/iphone/build/Intermediates/AppName.build/Release-iphoneos/AppName.build
/Script-000000000000000000000041.sh
[ERROR] (1 failure)
```

That file contains:

```
#!/bin/sh
/bin/bash "../../scripts/script-titanium-crashlytics.sh"
```

That script file doesn't exist there. In fact I cannot find it anywhere in the build folder. It is maybe not being copied from PROJECT/scripts/script-titanium-crashlytics.sh.

Seems similar to issue #25 but in my case, I do have firebase core installed and instantiated/configured.

Resolutions I tried:

* Putting the scripts/script-titanium-crashlytics.sh file inside the app folder instead of PROJECT
* In that file, hard coding the full path to the uploadDSYM executable
* Updating ti.runscriptphase.js with the full path to the script-titanium-crashlytics.sh file
* Updating ti.runscriptphase.js to use the `/bin/bash` shell path since I thought Catalina didn't include `sh`
* My App ID happens to contain a hyphen, which I thought might mess up the shell script. I tried various combinations of quotes around portions or all of the uploadDSYM command.

**Comment by skypanther** [comment]
In case it's not clear, I did create the PROJECT/scripts/script-titanium-crashlytics.sh folder & file per the readme instructions.

**Comment by skypanther** [comment]
I believe the problem is that the uploadDYSM tool is trying to upload to crashlytics servers that are offline or gone.

From the `ti build` command log output:
```
Error Domain=kCFErrorDomainCFNetwork Code=-1004 "Could not connect to the server." 
UserInfo={NSErrorFailingURLStringKey=https://api.crashlytics.com/spi/v1/platforms/ios/apps/com.bundle.id/built, 
NSErrorFailingURLKey=https://api.crashlytics.com/spi/v1/platforms/ios/apps/com.bundle.id/built, 
NSLocalizedDescription=Could not connect to the server.


MyApp.app.dSYM could not be uploaded statusCode
NSErrorFailingURLKey=https://cm.crashlytics.com/api/v3/platforms/ios/code_mappings
_kCFStreamErrorCodeKey=61
_kCFStreamErrorDomainKey=1
NSLocalizedDescription=Could not connect to the server.
```

**Comment by hansemannn** [comment]
I just moved Crashlytics to the latest version, which refactors the DSYM upload as well. Give it a try!

**Comment by jalenhunter** [comment]
Looks like you changes the files that the uploader hook runs in the script folder. Before it was:
`const scriptPath = '../../scripts/script-titanium-crashlytics.sh';`
and now the line looks like:
`const scriptArgs = `../../scripts/run -gsp ${googleServiceFile} -p ios\n../../scripts/upload-symbols -gsp ${googleServiceFile} -p ios ${path.join(`${dsymPaths}/${appName}.app.dSYM`)}`;`
The README has instructions for the original but not the new method. Can you update the README with what the "run" and the "upload-symbols" files are?

**Comment by tj-mc** [comment]
Same issue here. It seems there is no way to use this module on ios if we don't know what the run and upload symbol scripts are meant to be.
