### ISSUE TITLE
concurrent.TimeoutException issue on sdk 8.0.1+ and crash reporting issue on sdk 9.0.1+

### ISSUE THREAD

**Issue by MoEb6886** [hansemannn/titanium-crashlytics#31]
I've faced two types of issues on the 2 different configurations.
for : 
titanium sdk 8.0.1+
crashlytics : 1.1.2
firebase core: 5.0.1
TimeoutException happens on android app launching time .

`[ERROR] :  CrashlyticsCore: Failed to execute task.
[ERROR] :  CrashlyticsCore: java.util.concurrent.TimeoutException
[ERROR] :  CrashlyticsCore: 	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
[ERROR] :  CrashlyticsCore: 	at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
[ERROR] :  CrashlyticsCore: 	at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:320)
[ERROR] :  CrashlyticsCore: 	at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:300)
[ERROR] :  CrashlyticsCore: 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
[ERROR] :  CrashlyticsCore: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
[ERROR] :  CrashlyticsCore: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
[ERROR] :  CrashlyticsCore: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)`

I changed the configuration to :
titanium SDK: 9.0.1+
crashlytics : 1.1.2
firebase core: 5.0.1

the previous error does not happen anymore. all needed connections with firebase are done properly But just non-fatal errors are reporting to firebase dashboard, Not any crash reporting.

is this library compatible with Ti SDK 8.01+ ? does anybody have an idea, how can I fix this issue?

**Comment by hansemannn** [comment]
Please see the latest Android version!
