### ISSUE TITLE
Correct setup for iOS under v2.0.0

### ISSUE THREAD

**Issue by tj-mc** [hansemannn/titanium-crashlytics#33]
Hi there, thanks for your work on this module.
I'm upgrading to version 2.0.0 on iOS, but I'm slightly confused by the Readme, as it says you need to create the script-titanium-crashlytics.sh file. However, this file references `platform/Fabric.framework/uploadDSYM` which no longer exists in 2.0.0. Is this shell file still needed, or is this only for version <= 2.0.0?
Is there a replacement file that is needed for 2.0.0?
Thanks!

**Comment by tj-mc** [comment]
I discovered that this is missing from `ti.runscriptphase.js`, so guessing that is not needed. Could we clarify that this is not required in 2.0.0 in the Readme?

**Comment by hansemannn** [comment]
The file is not needed anymore, but the `run` and `upload-symbols` files are. I just updated the readme to reflect that!
