### ISSUE TITLE
Android Release 2.0.0 Module not found

### ISSUE THREAD

**Issue by cmtanko** [hansemannn/titanium-crashlytics#34]
I have added, in the tiapp.xml
<module platform="android" version ="2.0.0">ti.crashlytics</module>
and
 <meta-data android:name="io.fabric.ApiKey" android:value="my_key" /> inside <Application/>

It wont build my app anymore with this error message,
[ERROR] Could not find all required Titanium Modules:
[ERROR]    id: ti.crashlytics    version: 2.0.0  platform: android       deploy-type: test

if I add deploy-type: "development/production", it will build the app but 
var crashlytics = require("ti.crashlytics") , it error me module not found again.

Am I missing anything in the setup,

Environment:
Operating System
  Name                        = Mac OS X
  Version                     = 10.15.7
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 17179869184

Node.js
  Node.js Version             = 10.15.3
  npm Version                 = 6.4.1

Titanium CLI
  CLI Version                 = 5.2.2

Titanium SDK
  SDK Version                 = 8.3.1.GA
  Target Platform             = android

**Comment by hansemannn** [comment]
Updated to 2.0.1
