### ISSUE TITLE
Ti SDK 9.3.2GA + iOS 14 not working 

### ISSUE THREAD

**Issue by arunraj-qburst** [hansemannn/titanium-crashlytics#35]
It seems the library is not working (no crashes were reported in FB console) with the below methods.
`var Crashlytics = require('ti.crashlytics');`
Crashlytics.crash()  OR Crashlytics.log('some error')

"script" folder and its contents are already copied (https://github.com/hansemannn/titanium-crashlytics/tree/master/ios/helper )

I have done the steps mentioned in the doc and copied the files into 'script' folder. Is there anything else I should do in this regard ?

Update:
I was tying to take the archive build (iOS 14++) and the build precess in getting terminated due to script fail,
Here is the error message I am getting,
```
[ERROR] :  ** ARCHIVE FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	PhaseScriptExecution [Ti]\ Crashlytics /Users/arunrajsaraswathy/Documents/Appcelerator_Studio_Workspace/<<app name here>>/build/iphone/build/Intermediates/<<app name here>>.build/Release-iphoneos/<<app name here>>.build/Script-000000000000000000000047.sh
[ERROR] :  (1 failure)
```

**Environment:**
Ti SDK 9.3.2GA  
iOS 14+

![Screenshot 2021-05-25 at 12 49 47 PM](https://user-images.githubusercontent.com/12524585/119455940-c16eca80-bd57-11eb-8673-f3381318b82d.png)

**Comment by hansemannn** [comment]
Fixed by the latest version!
