### ISSUE TITLE
[GRADLE] Execution failed for task ':app:mergeDebugResources'. by Crashlytics 2.0.1

### ISSUE THREAD

**Issue by macasfaj** [hansemannn/titanium-crashlytics#36]
Node.js Version = 12.16.2
npm Version = 7.14.0
Titanium CLI
CLI Version = 5.2.2
Titanium SDK
SDK Version = 9.3.2.GA
Target Platform = android

It's still happening in 2.0.1 :/ Any help?? 

`ERROR] [GRADLE] [string/com.crashlytics.android.build_id] /Users/Migue/Documents/NubecitaSVN/supernova-mobile-client/build/android/app/src/main/res/values/crashlytics.xml [string/com.crashlytics.android.build_id] /Users/Migue/Documents/NubecitaSVN/supernova-mobile-client/build/android/app/build/generated/crashlytics/res/debug/values/com_crashlytics_build_id.xml: Resource and asset merger: Duplicate resources
[ERROR] [GRADLE] 
[ERROR] [GRADLE] FAILURE: Build failed with an exception.
[ERROR] [GRADLE] 
[ERROR] [GRADLE] * What went wrong:
[ERROR] [GRADLE] Execution failed for task ':app:mergeDebugResources'.
[ERROR] [GRADLE] > [string/com.crashlytics.android.build_id] /Users/Migue/Documents/NubecitaSVN/supernova-mobile-client/build/android/app/src/main/res/values/crashlytics.xml   [string/com.crashlytics.android.build_id] /Users/Migue/Documents/NubecitaSVN/supernova-mobile-client/build/android/app/build/generated/crashlytics/res/debug/values/com_crashlytics_build_id.xml: Error: Duplicate resources
[ERROR] [GRADLE] 
[ERROR] [GRADLE] * Try:
[ERROR] [GRADLE] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[ERROR] [GRADLE] 
[ERROR] [GRADLE] * Get more help at https://help.gradle.org
[ERROR] [GRADLE] 
[ERROR] [GRADLE] BUILD FAILED in 4s
[INFO]  [GRADLE] 24 actionable tasks: 24 executed
[ERROR] "gradlew" tool returned exit code: 1
Process exited with 1
The terminal process terminated with exit code: 1.`

**Comment by macasfaj** [comment]
Hi there, using last release, we get this error in crashlytics panel

ti.crashlytics.TitaniumCrashlyticsModule.onAppCreate (TitaniumCrashlyticsModule.java:50)
java.lang.reflect.Method.invoke (Method.java)
com.gosupernova.app.SupernovaApplication.onCreate (SupernovaApplication.java:666)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
arrow_drop_down
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

Any idea?? @m1ga @hansemannn

**Comment by m1ga** [comment]
Fixed in the latest version :+1:
