### ISSUE TITLE
Android: hook path in home directory

### ISSUE THREAD

**Issue by m1ga** [hansemannn/titanium-crashlytics#45]
When compiling with Atom (didn't check VSCode) the path of the hook will be wrong:
https://github.com/hansemannn/titanium-crashlytics/blob/master/android/hooks/gradle_plugins.js#L22

Atom:
`/home/miga/build/android/build.gradle` :x: 

using the CLI inside the app folder:
`/home/miga/dev/titanium/test_firebase_messaging/build/android/build.gradle` :heavy_check_mark: 

We might need a better way to check for the project dir

**Comment by jordanbisato** [comment]
Same problem here, but with a little difference on the path on atom.

Atom:
`/build/android/build.gradle` ❌

using the CLI inside the app folder:
`/Users/jordanbisato/Projetos/CVP-Aplicativo-Front/build/android/build.gradle` ✔️

**Comment by m1ga** [comment]
just tested it with Atom and VSCode. Looks like it is only an Atom issue so I'll move the issue to the package and close this one.

New issue: https://github.com/appcelerator/atom-appcelerator-titanium/issues/527
