### ISSUE TITLE
iOS installation help

### ISSUE THREAD

**Issue by Wingee** [hansemannn/titanium-crashlytics#5]
When you say the following:

Create a new folder scripts/ in your project root
Inside scripts/, create a script-titanium-crashlytics.sh with the following contents (replace the version with your version):

With an Alloy project should the scripts folder be inside the app folder? or at the same level as the apps folder?

**Comment by sed76** [comment]
For me, it works when `scripts/` folder at the same level as the `app/` .

**Comment by hansemannn** [comment]
Yes, always the root directory.

**Comment by Wingee** [comment]
I've followed these instructions, but I see no evidence in the code that it's worked. (I also get no data in Firebase)

Should there be anything in the console to suggest script-titanium-crashlytics.sh has run successfully? Or that ../../modules/iphone/ti.crashlytics/1.1.1/platform/Fabric.framework/run has done anything?

I'm building with 7.3.1GA and Crashlytics 1.1.1

**Comment by Wingee** [comment]
I've tried a brand new project and the problem still persists. See my screenshot below of the structure. 
![screen shot 2018-09-18 at 08 50 47](https://user-images.githubusercontent.com/813793/45672427-027e9d80-bb20-11e8-8617-c8f860920d58.png)

**Comment by Wingee** [comment]
@hansemannn  I thought I'd try with the demo app provided here: https://github.com/hansemannn/titanium-crashlytics-demo

I still can't get Fabric to see it. Here's the screenshot on Fabric:

![screen shot 2018-09-19 at 16 32 32](https://user-images.githubusercontent.com/813793/45764138-f1ba4e80-bc29-11e8-9d1d-1f50bc6a5e53.png)

I run the app, click the button that creates the crash but still Fabric says it can't see it

Any other ideas?

**Comment by Wingee** [comment]
I get the same issue on Firebase, the console says it's waiting for the app to communicate with it:

![screen shot 2018-09-20 at 16 54 26](https://user-images.githubusercontent.com/813793/45830852-e5032c80-bcf5-11e8-9ab5-fb260e9d5536.png)

I'd appreciate it you could open this issue again as I could really do with the help.

Thanks

**Comment by ptsequeira** [comment]
Hi @hansemannn 

I tried the demo project, a new project but nothings works. The script-titanium-crashlytics.sh does not seem to be running. Any ideias?

Thanks

**Comment by marconealberto** [comment]
Same issue here, I don't see the script added to the build phases. Anyone had better luck?

**Comment by jamie1192** [comment]
Nope no luck for me either, completely broken and does not work at all. 

No reply from author on any of the issues so this is a dead project.
