### ISSUE TITLE
Crashlytics website cant find app

### ISSUE THREAD

**Issue by ericpolkadoc** [hansemannn/titanium-crashlytics#6]
Hi,

I've followed your instructions, but having some issues -- when I run the app, Crashlytics can't find it, and won't add it to the dashboard.   This just keeps spinning.

Build and Run APPNAME
"We are looking for your app to confirm that it's activated"
That's not the right app (link)
- spinning wheel -

Just to make sure I understand the full native process, I've built a native iOS test app, and added Crashlytics via a Pod, and everything works, the test app gets added to my Crashlytics dashboard.  

For the installation in my app, per your instructions, I've done the following:
- built the ios module, v1.1.1, installed in in my app project
- created the script folder in my project root, added script-titanium-crashlytics.sh
- in script-titanium-crashlytics.sh, Ive added my ApiKey and Secret, updated with my version number 1.1.1
- added the Fabric section with the ApiKey to my tiapp.xml

Then in my alloy.js I added the require("ti.crashlytics") (is is necessary to uses es6 import?)

when I build and launch, the spinner on the activation confirmation just keeps spinning.

if I run any of the api methods, ie crash() or throwException(), that works in the app.

I've built a simple test app as well, same output.

any thoughts on what i might be doing wrong?

**Comment by amigoni** [comment]
I have the exact same issue. App doesn't register with dashboard. Neither iOS nor Android. Also used required not ES6

**Comment by sschueller** [comment]
Same issue here

**Comment by hansemannn** [comment]
Thanks for the input! The run-script injection script needed a little update. Working now!

<img width="764" alt="bildschirmfoto 2019-02-25 um 09 05 36" src="https://user-images.githubusercontent.com/10667698/53322921-18696900-38dd-11e9-9fe4-9a84a2dd4197.png">

**Comment by caspahouzer** [comment]
stuck in the same situation as @ericpolkadoc but using version 1.2.2
