### ISSUE TITLE
Android: Small info for the next update

### ISSUE THREAD

**Issue by m1ga** [hansemannn/titanium-crashlytics#61]
Just reminder for the next update:

https://github.com/firebase/firebase-android-sdk/issues/4223
Don't use 18.3.0, go to 18.3.1 (or higher)

**Comment by hansemannn** [comment]
Yep, saw the banner as well

**Comment by m1ga** [comment]
18.3.2 is already available, so I'll close this one. 

Changelog:
* 18.3.1: Fixed an [issue](https://github.com/firebase/firebase-android-sdk/issues/4223) in v18.3.0 that caused a NoClassDefFoundError in specific cases.
* 18.3.2 only fixed a NDK issue
