### ISSUE TITLE
Android Issue When Resuming Activity

### ISSUE THREAD

**Issue by jwogan5** [hansemannn/titanium-crashlytics#7]
So I implemented the 1.1.1 version of the module and it works great until I run ti.barcode which starts a new activity.  When I close the barcode scanner or anything else that creates a new activity the crash of crashlytics happens where it needs to be registered and gives the whole error like below.

[ERROR] CrashlyticsCore: This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
[ERROR] CrashlyticsCore: install an Android build tool and ask a team member to invite you to this app's organization.

I was going to look at your 1.1.1 version code but that is not what I can view from github. I cloned the repo but the code is the 1.1.0 version and 1.1.1 is only in the releases where you can't view the actual module file code.

I think that the Fabric initialization needs to occur on the onResume lifecycle event instead of the onStart if that is still how 1.1.1 is written.  This would allow the module to restart itself everytime the main activity is running.

Let me know if that will work and if so can you update github with the 1.1.1 code so I can make the change.

Thanks,

**Comment by hansemannn** [comment]
@jwogan5 Can you apply that fix?

**Comment by Sean-Brown-Digi** [comment]
@hansemannn is that version 1.1.1? How come there are newer versions of the iOS module but not Android?

**Comment by hansemannn** [comment]
Please see the latest Android version!
