### ISSUE TITLE
Unable to install module for iOS

### ISSUE THREAD

**Issue by cmtanko** [hansemannn/titanium-crashlytics#70]
I'm getting following error on iOS

`[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEPLOYTYPE=test')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_LOG_SERVER_PORT=52672')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_VERSION=12.2.1')
[E`

using latest release module

**Comment by hansemannn** [comment]
That are just warnings bubbled up from the actual error. Can you share your full trace log? The actual error starts with "error:"
