### ISSUE TITLE
Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps

### ISSUE THREAD

**Issue by sandeep14** [hansemannn/titanium-crashlytics#8]
Hi,

I have using user module in my appcelerator project. as per documentation I have added io.fabric.ApiKey in metadata . (it is my firebase app's api key). 
after running project. I have got below error

[INFO] :   FA: Tag Manager is not found and thus will not be used
[INFO] :   CrashlyticsCore: Initializing Crashlytics 2.6.3.25
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.test.test.TestActivity@7756f13
[INFO] :   DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
[INFO] :   DecorView: setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.test.test
[INFO] :   Adreno: QUALCOMM build                   : 934dff6, Ie4790512f3
[INFO] :   Adreno: Build Date                       : 04/16/18
[INFO] :   Adreno: OpenGL ES Shader Compiler Version: XE031.09.00.04
[INFO] :   Adreno: Local Branch                     :
[INFO] :   Adreno: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.01.02.269.051
[INFO] :   Adreno: Remote Branch                    : NONE
[INFO] :   Adreno: Reconstruct Branch               : NOTHING
[INFO] :   OpenGLRenderer: Initialized EGL, version 1.4
[ERROR] :  Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.test.test/settings
[ERROR] :  Answers: Failed to retrieve settings

I  have tried two option

1) https://stackoverflow.com/questions/49192218/failed-to-retrieve-settings-from-https-settings-crashlytics-com-spi-v2-platfor
 
but unble to find   " Firebase Console > Project Settings > Account Linking > Fabric " this path in firebase console

2)https://fabric.io/kits/ios/crashlytics

here we unable to add app, as we are using appcelerator, it provide solution to native android/ios 

How can we fix above issue, Please help me

**Comment by jalenhunter** [comment]
@sandeep14 What fixed the issue for you?
