### ISSUE TITLE
Crashlytics.crash() Method not working

### ISSUE THREAD

**Issue by sandeep14** [hansemannn/titanium-crashlytics#9]
Hi ,
I have using latest version 1.1.1 of crashlytics

when we hit Crashlytics.crash()  then we get below error
[ERROR] :  TiExceptionHandler: (main) [3363,3363] 	 Crashlytics.crash();
[ERROR] :  TiExceptionHandler:               ^
[ERROR] :  TiExceptionHandler: Error: length=2; index=10
[ERROR] :  TiExceptionHandler:     at Label.eval (eval at Module._compile (/app.js:728:13), <anonymous>:33:15)
[ERROR] :  TiExceptionHandler:     at Label.value (ti:/events.js:49:21)
[ERROR] :  TiExceptionHandler:     at Label.value (ti:/events.js:101:19)
[ERROR] :  TiExceptionHandler:
[ERROR] :  TiExceptionHandler:     com.crashlytics.android.core.CrashTest.indexOutOfBounds(CrashTest.java:30)
[ERROR] :  TiExceptionHandler:     com.crashlytics.android.core.CrashlyticsCore.crash(CrashlyticsCore.java:622)
[ERROR] :  TiExceptionHandler:     com.crashlytics.android.Crashlytics.crash(Crashlytics.java:323)
[ERROR] :  TiExceptionHandler:     ti.crashlytics.TitaniumCrashlyticsModule.crash(TitaniumCrashlyticsModule.java:47)
[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)
[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:979)
[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1208)
[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:401)
[ERROR]:   TiExceptionHandler:     android.os.Handler.dispatchMessage (Trades.java:98)
[INFO] :   DecorView: setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.test.test
[ERROR] :  V8Exception: Exception occurred at undefined:33: Uncaught Error: length=2; index=10

I don't know why this error is coming or I am doing something wrong Please help me on this.

**Comment by hansemannn** [comment]
The whole concept of this method is to simulate a crash… It works fine!
